### PR TITLE
remove language suggesting refunds for domain registration are possible

### PR DESCRIPTION
**Pull request by sudoforge**
**Issue**: #2 

**Description of changes**:
The documentation for deleting a domain suggests that refunds can be received for domain registration. This is not the case, as confirmed with an AWS Support Agent.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by skralik** [comment]
Hi,
Thanks for your feedback. I don’t want to remove the note, because I want readers to know that domain registration fees are not refundable, even when the domain registration is deleted. Can you help me understand what’s confusing about the existing note?
Thanks.
Scott

**Comment by sudoforge** [comment]
Hey there.

I apologize if my commit message was not clear enough.

The note in question is definitely accurate - domain registration fees are _not_ refundable after the deletion of the domain. The problem I find with this particular language...

> If you delete a domain name registration before the registration was scheduled to expire, we will not refund the registration fee

... is that it implies that one might be able to receive a refund _before_ deleting the domain. This is not the case, as you may be aware - AWS will not refund domain registration fees at all, regardless of whether or not they have been deleted.

Does that help make the issue more clear?

> I don’t want to remove the note, because I want readers to know that domain registration fees are not refundable

Perhaps we should add specific language surrounding refunds - maybe in its own document? Something akin to: "Unfortunately, domain registration fees cannot be refunded."

**Comment by skralik** [comment]
Thanks for the additional information. As you can imagine, several folks review any text related to fees. Having looked over this again, we’ve decided to keep the current wording. But thank you again for bringing this to our attention and prompting us to take a look.

**Comment by sudoforge** [comment]
Is my point getting across? This note is the _only_ note in the route53 docs mentioning the word "refund". I feel that it's pretty cut and dry that...

> If you delete a domain name registration before the registration was scheduled to expire, we will not refund the registration fee

... is effectively saying that refunds for domain registration fees are possible if you don't delete the domain. Which is not the case. As I said -- this note is factually correct, **but it alludes to refunds being possible if the domain is not deleted**, which is incorrect.

**Comment by skralik** [comment]
Hi,

I understand your logic. However, the documentation about deleting a domain registration isn't intended to be a comprehensive explanation of billing, it’s intended to explain all of the relevant aspects of deleting a domain registration.

Given the subject of the topic, we want to answer the specific question of how deleting a domain registration affects customers' bills. (After the domain registration service launched, customers repeatedly asked about refunds for deleted domains; the topic originally didn't mention refunds at all.) If we change the text to "Registration fees cannot be refunded", it doesn't specifically address the issue of how deleting a domain registration affects billing. The proposed text could also cause customers to wonder how that text is related to deleting a domain registration.

After extensive discussion, we've decided to leave the text as is for now. We'll certainly revisit that if we get more feedback.

Scott

**Pull request closed without merging**
